#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
WORKSPACE_ROOT="$(cd "${SCRIPT_DIR}/../../.." && pwd)"
COMPAT_DIR="${WORKSPACE_ROOT}/docs/compatibility"

STATUS_SCRIPT="${SCRIPT_DIR}/build_command_status_matrix.sh"
MATURITY_SCRIPT="${SCRIPT_DIR}/build_command_maturity_matrix.sh"
SUBSET_SCRIPT="${SCRIPT_DIR}/redis_runtest_external_subset.sh"

STATUS_CSV="${STATUS_CSV:-${COMPAT_DIR}/redis-command-status.csv}"
MATURITY_CSV="${MATURITY_CSV:-${COMPAT_DIR}/redis-command-maturity.csv}"
REPORT_MD="${REPORT_MD:-${COMPAT_DIR}/compatibility-report.md}"

RESULT_ROOT="${RESULT_ROOT:-${SCRIPT_DIR}/results/compatibility-report-$(date +%Y%m%d-%H%M%S)}"
SUBSET_RESULT_DIR="${SUBSET_RESULT_DIR:-${RESULT_ROOT}/redis-runtest-external-subset}"
SUBSET_SUMMARY_CSV="${SUBSET_RESULT_DIR}/summary.csv"

if [[ ! -x "${STATUS_SCRIPT}" ]]; then
    echo "missing executable: ${STATUS_SCRIPT}" >&2
    exit 1
fi
if [[ ! -x "${MATURITY_SCRIPT}" ]]; then
    echo "missing executable: ${MATURITY_SCRIPT}" >&2
    exit 1
fi
if [[ ! -x "${SUBSET_SCRIPT}" ]]; then
    echo "missing executable: ${SUBSET_SCRIPT}" >&2
    exit 1
fi

mkdir -p "${RESULT_ROOT}"

echo "[1/4] building declared command status matrix..."
"${STATUS_SCRIPT}"

echo "[2/4] building command maturity matrix from yaml..."
"${MATURITY_SCRIPT}"

echo "[3/4] running redis runtest external subset..."
RESULT_DIR="${SUBSET_RESULT_DIR}" "${SUBSET_SCRIPT}"

if [[ ! -f "${STATUS_CSV}" ]]; then
    echo "status csv not found: ${STATUS_CSV}" >&2
    exit 1
fi
if [[ ! -f "${MATURITY_CSV}" ]]; then
    echo "maturity csv not found: ${MATURITY_CSV}" >&2
    exit 1
fi
if [[ ! -f "${SUBSET_SUMMARY_CSV}" ]]; then
    echo "subset summary csv not found: ${SUBSET_SUMMARY_CSV}" >&2
    exit 1
fi

redis_total="$(awk -F, 'NR>1 && $3=="1" {c++} END {print c+0}' "${STATUS_CSV}")"
garnet_total="$(awk -F, 'NR>1 && $4=="1" {c++} END {print c+0}' "${STATUS_CSV}")"
supported_declared="$(awk -F, 'NR>1 && $2=="SUPPORTED_DECLARED" {c++} END {print c+0}' "${STATUS_CSV}")"
not_implemented="$(awk -F, 'NR>1 && $2=="NOT_IMPLEMENTED" {c++} END {print c+0}' "${STATUS_CSV}")"
extensions="$(awk -F, 'NR>1 && $2=="GARNET_EXTENSION" {c++} END {print c+0}' "${STATUS_CSV}")"

full_total="$(awk -F, 'NR>1 && $2=="SUPPORTED_DECLARED" && $5=="FULL" {c++} END {print c+0}' "${MATURITY_CSV}")"
partial_total="$(awk -F, 'NR>1 && $2=="SUPPORTED_DECLARED" && $5=="PARTIAL_MINIMAL" {c++} END {print c+0}' "${MATURITY_CSV}")"
disabled_total="$(awk -F, 'NR>1 && $2=="SUPPORTED_DECLARED" && $5=="DISABLED" {c++} END {print c+0}' "${MATURITY_CSV}")"
full_ratio="$(awk -v full="${full_total}" -v total="${supported_declared}" 'BEGIN { if (total==0) print "0.00"; else printf "%.2f", (full*100.0)/total }')"

subset_pass="$(awk -F, 'NR>1 && $2=="PASS" {c++} END {print c+0}' "${SUBSET_SUMMARY_CSV}")"
subset_fail="$(awk -F, 'NR>1 && $2=="FAIL" {c++} END {print c+0}' "${SUBSET_SUMMARY_CSV}")"
subset_total="$(awk -F, 'NR>1 {c++} END {print c+0}' "${SUBSET_SUMMARY_CSV}")"

echo "[4/4] generating compatibility report..."
{
    echo "# Compatibility Report (Auto-Generated)"
    echo
    echo "> This file is generated by \`garnet-rs/tests/interop/build_compatibility_report.sh\`."
    echo "> Do not edit manually."
    echo
    echo "- Generated at: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    echo "- Command declaration source: \`docs/compatibility/redis-command-status.csv\`"
    echo "- Maturity source: \`docs/compatibility/command-implementation-status.yaml\` -> \`docs/compatibility/redis-command-maturity.csv\`"
    echo "- External behavioral probe: \`garnet-rs/tests/interop/redis_runtest_external_subset.sh\`"
    echo "- External probe artifacts: \`${SUBSET_RESULT_DIR}\`"
    echo
    echo "## Declaration Coverage Snapshot"
    echo
    echo "- Redis baseline command count: \`${redis_total}\`"
    echo "- Garnet declared command count: \`${garnet_total}\`"
    echo "- \`SUPPORTED_DECLARED\`: \`${supported_declared}\`"
    echo "- \`NOT_IMPLEMENTED\`: \`${not_implemented}\`"
    echo "- \`GARNET_EXTENSION\`: \`${extensions}\`"
    echo
    echo "## Implementation Maturity Snapshot"
    echo
    echo "- \`FULL\`: \`${full_total}\`"
    echo "- \`PARTIAL_MINIMAL\`: \`${partial_total}\`"
    echo "- \`DISABLED\`: \`${disabled_total}\`"
    echo "- Full ratio over declared commands: \`${full_ratio}%\`"
    echo
    echo "## External Subset Probe Snapshot"
    echo
    echo "- Cases: \`${subset_total}\`"
    echo "- PASS: \`${subset_pass}\`"
    echo "- FAIL: \`${subset_fail}\`"
    echo
    echo "| Case | Status | Details |"
    echo "|---|---|---|"
    awk -F, 'NR>1 {printf("| `%s` | `%s` | %s |\n", $1, $2, $3)}' "${SUBSET_SUMMARY_CSV}"
    echo
    echo "## Non-Full Commands (Declared Surface With Known Gaps)"
    echo
    echo "| Command | Maturity | Comment |"
    echo "|---|---|---|"
    awk -F, '
    NR>1 && $2=="SUPPORTED_DECLARED" && $5!="FULL" {
        comment = ($6 == "" ? "-" : $6);
        printf("| `%s` | `%s` | %s |\n", $1, $5, comment);
    }
    ' "${MATURITY_CSV}"
} > "${REPORT_MD}"

echo "wrote ${REPORT_MD}"
echo "subset_result_dir=${SUBSET_RESULT_DIR}"
