use std::sync::OnceLock;
use std::sync::atomic::AtomicUsize;
use std::sync::atomic::Ordering;

use tsavorite::DeleteOperationError;
use tsavorite::PageManagerError;
use tsavorite::PageResidencyError;
use tsavorite::ReadOperationError;
use tsavorite::RmwOperationError;
use tsavorite::UpsertOperationError;

const GARNET_LOG_STORAGE_FAILURES_ENV: &str = "GARNET_LOG_STORAGE_FAILURES";
const STORAGE_FAILURE_LOG_LIMIT: usize = 64;
static STORAGE_FAILURE_LOG_ENABLED: OnceLock<bool> = OnceLock::new();
static STORAGE_FAILURE_LOG_COUNT: AtomicUsize = AtomicUsize::new(0);

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum RequestExecutionError {
    WrongArity {
        command: &'static str,
        expected: &'static str,
    },
    UnknownCommand,
    UnknownSubcommand,
    NoSuchKey,
    NoGroup,
    BusyGroup,
    BusyKey,
    BusyScript,
    InvalidDumpPayload,
    InvalidArguments,
    SyntaxError,
    InvalidExpireTime,
    InvalidGetExExpireTime,
    InvalidExpireCommandExpireTime,
    InvalidPExpireCommandExpireTime,
    WrongType,
    InvalidObject,
    KeyShouldBeStringForConditionalDelete,
    InvalidConditionalDeleteCondition,
    DigestMustBeExactly16HexCharacters,
    InvalidMsetexNumkeysValue,
    WrongNumberOfKeyValuePairs,
    StorageBusy,
    StorageCapacityExceeded,
    StorageFailure,
    CommandDisabled {
        command: &'static str,
    },
    ValueNotInteger,
    TimeoutNotIntegerOrOutOfRange,
    ValueNotFloat,
    MinOrMaxNotFloat,
    MinOrMaxNotValidStringRangeItem,
    WeightValueNotFloat,
    HashMandatoryFieldsArgumentMissing,
    HashNumfieldsParameterMustMatchArguments,
    HashNumberOfFieldsMustBePositiveInteger,
    HashNumFieldsParameterShouldBeGreaterThanZero,
    HashInvalidNumberOfFields,
    HashUnknownArgument,
    HashMissingExpireTime,
    HashOnlyOneOfFxxFnxArgumentsCanBeSpecified,
    HashOnlyOneOfHsetexExpireArgumentsCanBeSpecified,
    HashOnlyOneOfHgetexExpireArgumentsCanBeSpecified,
    HashMultipleConditionFlagsSpecified,
    HashFieldsKeywordSpecifiedMultipleTimes,
    NumkeysMustBeGreaterThanZero,
    CountMustBeGreaterThanZero,
    SlowlogCountMustBeGreaterThanOrEqualToMinusOne,
    XautoclaimCountMustBeGreaterThanZero,
    UnsupportedUnit,
    ValueOutOfRange,
    ValueOutOfRangePositive,
    StringExceedsMaximumAllowedSize,
    GeoSearchRequiresOrigin,
    GeoSearchRequiresShape,
    GeoAnyRequiresCount,
    LposRankZero,
    TimeoutIsNegative,
    IndexOutOfRange,
    IncrementOverflow,
    AuthNotEnabled,
    InvalidFirstDbIndex,
    InvalidSecondDbIndex,
    DbIndexOutOfRange,
    SourceDestinationObjectsSame,
    WaitAofAppendOnlyDisabled,
    ClusterSupportDisabled,
    FunctionLibraryAlreadyExists,
    FunctionLibraryNotFound,
    FunctionNameAlreadyExists,
    FunctionNotFound,
    FunctionNotReadOnly,
    ScriptTooBig,
    ScriptExecutionTimedOut,
    NoScript,
    ScriptingDisabled,
    IncrementWouldProduceNanOrInfinity,
    ValueIsNanOrInfinity,
    NegativeKeyCount,
    AtLeastOneInputKey {
        command: &'static str,
    },
    NumberOfKeysCantBeGreaterThanArgs,
    LimitCantBeNegative,
    InvalidStreamId,
    UnbalancedXreadStreamList,
    UnbalancedXreadgroupStreamList,
    ClaimOptionOnlySupportedByXreadgroup,
    MinIdleTimeNotInteger,
    MinIdleTimeMustBePositiveInteger,
    XGroupKeyMustExist,
    EntriesReadMustBePositiveOrMinusOne,
    XaddIdEqualOrSmallerThanTopItem,
    XsetidEntriesAddedMustBePositive,
    XsetidSmallerThanProvidedMaxDeletedId,
    XsetidSmallerThanCurrentMaxDeletedId,
    XsetidSmallerThanTopItem,
    XsetidEntriesAddedSmallerThanLength,
    IdmpSpecifiedMultipleTimes,
    IdmpAutoRequiresNonEmptyProducerId,
    IdmpRequiresNonEmptyProducerId,
    IdmpRequiresNonEmptyIid,
    IdmpRequiresAutoGeneratedId,
    XcfgsetRequiresAtLeastOneParameter,
    XcfgsetDurationSpecifiedMultipleTimes,
    XcfgsetMaxsizeSpecifiedMultipleTimes,
    IdmpDurationMustBeBetween,
    IdmpMaxsizeMustBeBetween,
    NumberOfIdsMustBePositiveInteger,
    NumidsParameterMustMatchArguments,
    ResultingScoreNotANumber,
    SortScoreNotDouble,
}

impl RequestExecutionError {
    pub fn info_error_name(self) -> &'static [u8] {
        match self {
            Self::NoGroup => b"NOGROUP",
            Self::BusyGroup => b"BUSYGROUP",
            Self::BusyKey => b"BUSYKEY",
            Self::BusyScript => b"BUSY",
            Self::WrongType => b"WRONGTYPE",
            Self::InvalidObject => b"INVALIDOBJ",
            Self::NoScript => b"NOSCRIPT",
            _ => b"ERR",
        }
    }

    pub fn append_resp_error(self, response_out: &mut Vec<u8>) {
        match self {
            Self::WrongArity { command, .. } => append_error(
                response_out,
                &format!(
                    "ERR wrong number of arguments for '{}' command",
                    command.to_ascii_lowercase()
                ),
            ),
            Self::UnknownCommand => append_error(response_out, "ERR unknown command"),
            Self::UnknownSubcommand => append_error(response_out, "ERR unknown subcommand"),
            Self::NoSuchKey => append_error(response_out, "ERR no such key"),
            Self::NoGroup => append_error(response_out, "NOGROUP No such key or consumer group"),
            Self::BusyGroup => {
                append_error(response_out, "BUSYGROUP Consumer Group name already exists")
            }
            Self::BusyKey => append_error(response_out, "BUSYKEY Target key name already exists."),
            Self::BusyScript => append_error(
                response_out,
                "BUSY Redis is busy running a script. You can only call FUNCTION KILL or SCRIPT KILL.",
            ),
            Self::InvalidDumpPayload => append_error(
                response_out,
                "ERR DUMP payload version or checksum are wrong",
            ),
            Self::InvalidArguments => {
                append_error(response_out, "ERR Invalid arguments specified for command")
            }
            Self::SyntaxError => append_error(response_out, "ERR syntax error"),
            Self::InvalidExpireTime => {
                append_error(response_out, "ERR invalid expire time in 'set' command")
            }
            Self::InvalidGetExExpireTime => {
                append_error(response_out, "ERR invalid expire time in 'getex' command")
            }
            Self::InvalidExpireCommandExpireTime => {
                append_error(response_out, "ERR invalid expire time in 'expire' command")
            }
            Self::InvalidPExpireCommandExpireTime => {
                append_error(response_out, "ERR invalid expire time in 'pexpire' command")
            }
            Self::WrongType => append_error(
                response_out,
                "WRONGTYPE Operation against a key holding the wrong kind of value",
            ),
            Self::KeyShouldBeStringForConditionalDelete => append_error(
                response_out,
                "ERR Key should be of string type if conditions are specified",
            ),
            Self::InvalidConditionalDeleteCondition => append_error(
                response_out,
                "ERR Invalid condition. Use IFEQ, IFNE, IFDEQ, or IFDNE",
            ),
            Self::DigestMustBeExactly16HexCharacters => append_error(
                response_out,
                "ERR must be exactly 16 hexadecimal characters",
            ),
            Self::InvalidMsetexNumkeysValue => {
                append_error(response_out, "ERR invalid numkeys value")
            }
            Self::WrongNumberOfKeyValuePairs => {
                append_error(response_out, "ERR wrong number of key-value pairs")
            }
            Self::InvalidObject => {
                append_error(response_out, "INVALIDOBJ Corrupted HLL object detected")
            }
            Self::StorageBusy => append_error(response_out, "ERR storage busy, retry later"),
            Self::StorageCapacityExceeded => append_error(
                response_out,
                "ERR storage capacity exceeded (increase max in-memory pages)",
            ),
            Self::StorageFailure => append_error(response_out, "ERR internal storage failure"),
            Self::CommandDisabled { command } => append_error(
                response_out,
                &format!("ERR {} is disabled in this server", command),
            ),
            Self::ValueNotInteger => {
                append_error(response_out, "ERR value is not an integer or out of range")
            }
            Self::HashMandatoryFieldsArgumentMissing => append_error(
                response_out,
                "ERR Mandatory argument FIELDS is missing or not at the right position",
            ),
            Self::HashNumfieldsParameterMustMatchArguments => append_error(
                response_out,
                "ERR The `numfields` parameter must match the number of arguments",
            ),
            Self::HashNumberOfFieldsMustBePositiveInteger => append_error(
                response_out,
                "ERR Number of fields must be a positive integer",
            ),
            Self::HashNumFieldsParameterShouldBeGreaterThanZero => append_error(
                response_out,
                "ERR Parameter numFields should be greater than 0",
            ),
            Self::HashInvalidNumberOfFields => {
                append_error(response_out, "ERR invalid number of fields")
            }
            Self::HashUnknownArgument => append_error(response_out, "ERR unknown argument"),
            Self::HashMissingExpireTime => append_error(response_out, "ERR missing expire time"),
            Self::HashOnlyOneOfFxxFnxArgumentsCanBeSpecified => append_error(
                response_out,
                "ERR Only one of FXX or FNX arguments can be specified",
            ),
            Self::HashOnlyOneOfHsetexExpireArgumentsCanBeSpecified => append_error(
                response_out,
                "ERR Only one of EX, PX, EXAT, PXAT or KEEPTTL arguments can be specified",
            ),
            Self::HashOnlyOneOfHgetexExpireArgumentsCanBeSpecified => append_error(
                response_out,
                "ERR Only one of EX, PX, EXAT, PXAT or PERSIST arguments can be specified",
            ),
            Self::HashMultipleConditionFlagsSpecified => {
                append_error(response_out, "ERR Multiple condition flags specified")
            }
            Self::HashFieldsKeywordSpecifiedMultipleTimes => {
                append_error(response_out, "ERR FIELDS keyword specified multiple times")
            }
            Self::TimeoutNotIntegerOrOutOfRange => append_error(
                response_out,
                "ERR timeout is not an integer or out of range",
            ),
            Self::ValueNotFloat => append_error(response_out, "ERR value is not a valid float"),
            Self::MinOrMaxNotFloat => append_error(response_out, "ERR min or max is not a float"),
            Self::MinOrMaxNotValidStringRangeItem => {
                append_error(response_out, "ERR min or max not valid string range item")
            }
            Self::WeightValueNotFloat => {
                append_error(response_out, "ERR weight value is not a float")
            }
            Self::NumkeysMustBeGreaterThanZero => {
                append_error(response_out, "ERR numkeys should be greater than 0")
            }
            Self::CountMustBeGreaterThanZero => {
                append_error(response_out, "ERR count should be greater than 0")
            }
            Self::SlowlogCountMustBeGreaterThanOrEqualToMinusOne => append_error(
                response_out,
                "ERR count should be greater than or equal to -1",
            ),
            Self::XautoclaimCountMustBeGreaterThanZero => {
                append_error(response_out, "ERR COUNT must be > 0")
            }
            Self::UnsupportedUnit => append_error(
                response_out,
                "ERR unsupported unit provided. please use M, KM, FT, MI",
            ),
            Self::ValueOutOfRange => append_error(response_out, "ERR value is out of range"),
            Self::ValueOutOfRangePositive => {
                append_error(response_out, "ERR value is out of range, must be positive")
            }
            Self::StringExceedsMaximumAllowedSize => append_error(
                response_out,
                "ERR string exceeds maximum allowed size (proto-max-bulk-len)",
            ),
            Self::GeoSearchRequiresOrigin => append_error(
                response_out,
                "ERR exactly one of FROMMEMBER or FROMLONLAT must be specified",
            ),
            Self::GeoSearchRequiresShape => append_error(
                response_out,
                "ERR exactly one of BYRADIUS and BYBOX must be specified",
            ),
            Self::GeoAnyRequiresCount => {
                append_error(response_out, "ERR ANY option requires COUNT option")
            }
            Self::LposRankZero => append_error(
                response_out,
                "ERR RANK can't be zero: use 1 to start from the first match, 2 from the second ... or use negative to start from the end of the list",
            ),
            Self::TimeoutIsNegative => append_error(response_out, "ERR timeout is negative"),
            Self::IndexOutOfRange => append_error(response_out, "ERR index out of range"),
            Self::IncrementOverflow => {
                append_error(response_out, "ERR increment or decrement would overflow")
            }
            Self::AuthNotEnabled => append_error(
                response_out,
                "ERR AUTH <password> called without any password configured for the default user. Are you sure your configuration is correct?",
            ),
            Self::InvalidFirstDbIndex => append_error(response_out, "ERR invalid first DB index"),
            Self::InvalidSecondDbIndex => append_error(response_out, "ERR invalid second DB index"),
            Self::DbIndexOutOfRange => append_error(response_out, "ERR DB index is out of range"),
            Self::SourceDestinationObjectsSame => append_error(
                response_out,
                "ERR source and destination objects are the same",
            ),
            Self::WaitAofAppendOnlyDisabled => append_error(
                response_out,
                "ERR WAITAOF cannot be used when numlocal is set but appendonly is disabled.",
            ),
            Self::ClusterSupportDisabled => append_error(
                response_out,
                "ERR This instance has cluster support disabled",
            ),
            Self::FunctionLibraryAlreadyExists => {
                append_error(response_out, "ERR Library already exists")
            }
            Self::FunctionLibraryNotFound => append_error(response_out, "ERR Library not found"),
            Self::FunctionNameAlreadyExists => {
                append_error(response_out, "ERR Function already exists")
            }
            Self::FunctionNotFound => append_error(response_out, "ERR Function not found"),
            Self::FunctionNotReadOnly => append_error(
                response_out,
                "ERR Can not execute a script with write flag using *_ro command",
            ),
            Self::ScriptTooBig => append_error(
                response_out,
                "ERR script is larger than the configured max script size",
            ),
            Self::ScriptExecutionTimedOut => {
                append_error(response_out, "ERR script execution timed out")
            }
            Self::NoScript => append_error(
                response_out,
                "NOSCRIPT No matching script. Please use EVAL.",
            ),
            Self::ScriptingDisabled => {
                append_error(response_out, "ERR scripting is disabled in this server")
            }
            Self::IncrementWouldProduceNanOrInfinity => {
                append_error(response_out, "ERR increment would produce NaN or Infinity")
            }
            Self::ValueIsNanOrInfinity => {
                append_error(response_out, "ERR value is NaN or Infinity")
            }
            Self::NegativeKeyCount => {
                append_error(response_out, "ERR Number of keys can't be negative")
            }
            Self::AtLeastOneInputKey { command } => append_error(
                response_out,
                &format!("ERR at least 1 input key is needed for '{command}' command"),
            ),
            Self::NumberOfKeysCantBeGreaterThanArgs => append_error(
                response_out,
                "ERR Number of keys can't be greater than number of args",
            ),
            Self::LimitCantBeNegative => append_error(response_out, "ERR LIMIT can't be negative"),
            Self::InvalidStreamId => append_error(
                response_out,
                "ERR Invalid stream ID specified as stream command argument",
            ),
            Self::UnbalancedXreadStreamList => append_error(
                response_out,
                "ERR Unbalanced 'xread' list of streams: for each stream key an ID, '+', or '$' must be specified.",
            ),
            Self::UnbalancedXreadgroupStreamList => append_error(
                response_out,
                "ERR Unbalanced 'xreadgroup' list of streams: for each stream key an ID or '>' must be specified.",
            ),
            Self::ClaimOptionOnlySupportedByXreadgroup => append_error(
                response_out,
                "ERR The CLAIM option is only supported by XREADGROUP. You called XREAD instead.",
            ),
            Self::MinIdleTimeNotInteger => {
                append_error(response_out, "ERR min-idle-time is not an integer")
            }
            Self::MinIdleTimeMustBePositiveInteger => {
                append_error(response_out, "ERR min-idle-time must be a positive integer")
            }
            Self::XGroupKeyMustExist => append_error(
                response_out,
                "ERR The XGROUP subcommand requires the key to exist. Note that for CREATE you may want to use the MKSTREAM option to create an empty stream automatically.",
            ),
            Self::EntriesReadMustBePositiveOrMinusOne => append_error(
                response_out,
                "ERR value for ENTRIESREAD must be positive or -1",
            ),
            Self::XaddIdEqualOrSmallerThanTopItem => append_error(
                response_out,
                "ERR The ID specified in XADD is equal or smaller than the target stream top item",
            ),
            Self::XsetidEntriesAddedMustBePositive => {
                append_error(response_out, "ERR entries_added must be positive")
            }
            Self::XsetidSmallerThanProvidedMaxDeletedId => append_error(
                response_out,
                "ERR The ID specified in XSETID is smaller than the provided max_deleted_entry_id",
            ),
            Self::XsetidSmallerThanCurrentMaxDeletedId => append_error(
                response_out,
                "ERR The ID specified in XSETID is smaller than current max_deleted_entry_id",
            ),
            Self::XsetidSmallerThanTopItem => append_error(
                response_out,
                "ERR The ID specified in XSETID is smaller than the target stream top item",
            ),
            Self::XsetidEntriesAddedSmallerThanLength => append_error(
                response_out,
                "ERR The entries_added specified in XSETID is smaller than the target stream length",
            ),
            Self::IdmpSpecifiedMultipleTimes => append_error(
                response_out,
                "ERR syntax error, IDMP/IDMPAUTO specified multiple times",
            ),
            Self::IdmpAutoRequiresNonEmptyProducerId => append_error(
                response_out,
                "ERR syntax error, IDMPAUTO requires a non-empty producer ID",
            ),
            Self::IdmpRequiresNonEmptyProducerId => append_error(
                response_out,
                "ERR syntax error, IDMP requires a non-empty producer ID",
            ),
            Self::IdmpRequiresNonEmptyIid => append_error(
                response_out,
                "ERR syntax error, IDMP requires a non-empty idempotent ID",
            ),
            Self::IdmpRequiresAutoGeneratedId => append_error(
                response_out,
                "ERR syntax error, IDMP/IDMPAUTO can be used only with auto-generated IDs",
            ),
            Self::XcfgsetRequiresAtLeastOneParameter => append_error(
                response_out,
                "ERR At least one parameter of IDMP-DURATION and IDMP-MAXSIZE should be specified",
            ),
            Self::XcfgsetDurationSpecifiedMultipleTimes => {
                append_error(response_out, "ERR IDMP-DURATION specified multiple times")
            }
            Self::XcfgsetMaxsizeSpecifiedMultipleTimes => {
                append_error(response_out, "ERR IDMP-MAXSIZE specified multiple times")
            }
            Self::IdmpDurationMustBeBetween => append_error(
                response_out,
                "ERR IDMP-DURATION must be between 1 and 86400 seconds",
            ),
            Self::IdmpMaxsizeMustBeBetween => append_error(
                response_out,
                "ERR IDMP-MAXSIZE must be between 1 and 10000 entries",
            ),
            Self::NumberOfIdsMustBePositiveInteger => {
                append_error(response_out, "ERR Number of IDs must be a positive integer")
            }
            Self::NumidsParameterMustMatchArguments => append_error(
                response_out,
                "ERR The `numids` parameter must match the number of arguments",
            ),
            Self::ResultingScoreNotANumber => {
                append_error(response_out, "ERR resulting score is not a number (NaN)")
            }
            Self::SortScoreNotDouble => append_error(
                response_out,
                "ERR One or more scores can't be converted into double",
            ),
        }
    }
}

fn storage_failure_logging_enabled() -> bool {
    *STORAGE_FAILURE_LOG_ENABLED.get_or_init(|| {
        std::env::var(GARNET_LOG_STORAGE_FAILURES_ENV)
            .map(|value| !matches!(value.as_str(), "0" | "false" | "FALSE"))
            .unwrap_or(true)
    })
}

fn log_storage_failure(context: &str, detail: &str) {
    if !storage_failure_logging_enabled() {
        return;
    }

    let count = STORAGE_FAILURE_LOG_COUNT.fetch_add(1, Ordering::Relaxed);
    if count >= STORAGE_FAILURE_LOG_LIMIT {
        if count == STORAGE_FAILURE_LOG_LIMIT {
            eprintln!(
                "garnet-server storage failure logging suppressed after {} entries",
                STORAGE_FAILURE_LOG_LIMIT
            );
        }
        return;
    }

    let backtrace = std::backtrace::Backtrace::force_capture();
    eprintln!(
        "garnet-server storage failure [{}]: {}\nbacktrace:\n{}",
        context, detail, backtrace
    );
}

pub(super) fn storage_failure(context: &str, detail: &str) -> RequestExecutionError {
    log_storage_failure(context, detail);
    RequestExecutionError::StorageFailure
}

pub(super) fn map_read_error(error: ReadOperationError) -> RequestExecutionError {
    match error {
        ReadOperationError::PageManager(PageManagerError::BufferFull { .. }) => {
            RequestExecutionError::StorageCapacityExceeded
        }
        ReadOperationError::PageResidency(PageResidencyError::PageManager(
            PageManagerError::BufferFull { .. },
        )) => RequestExecutionError::StorageCapacityExceeded,
        ReadOperationError::PageResidency(PageResidencyError::NoEvictablePage { .. }) => {
            RequestExecutionError::StorageBusy
        }
        other => storage_failure("read", &format!("{other:?}")),
    }
}

pub(super) fn map_upsert_error(error: UpsertOperationError) -> RequestExecutionError {
    match error {
        UpsertOperationError::PageManager(PageManagerError::BufferFull { .. }) => {
            RequestExecutionError::StorageCapacityExceeded
        }
        UpsertOperationError::CompareExchangeConflict => RequestExecutionError::StorageBusy,
        other => storage_failure("upsert", &format!("{other:?}")),
    }
}

pub(super) fn map_delete_error(error: DeleteOperationError) -> RequestExecutionError {
    match error {
        DeleteOperationError::PageManager(PageManagerError::BufferFull { .. }) => {
            RequestExecutionError::StorageCapacityExceeded
        }
        DeleteOperationError::CompareExchangeConflict => RequestExecutionError::StorageBusy,
        other => storage_failure("delete", &format!("{other:?}")),
    }
}

pub(super) fn map_rmw_error(error: RmwOperationError) -> RequestExecutionError {
    match error {
        RmwOperationError::PageManager(PageManagerError::BufferFull { .. }) => {
            RequestExecutionError::StorageCapacityExceeded
        }
        RmwOperationError::CompareExchangeConflict => RequestExecutionError::StorageBusy,
        other => storage_failure("rmw", &format!("{other:?}")),
    }
}

fn append_error(response_out: &mut Vec<u8>, message: &str) {
    response_out.push(b'-');
    response_out.extend_from_slice(message.as_bytes());
    response_out.extend_from_slice(b"\r\n");
}
